#book_management.h global.h librarian.h library.h sign.h user.h
#global.c librarian.c library.c sign.c user.c


Library:global.o librarian.o library.o sign.o user.o
	gcc global.o librarian.o library.o sign.o user.o

global.o:global.c
	gcc -c global.c -o global.o

librarian.o:librarian.c
	gcc -c librarian.c -o librarian.o

library.o:library.c
	gcc -c library.c -o library.o

sign.o:sign.c
	gcc -c sign.c -o sign.o

library.o:library.c
	gcc -c library.c -o library.o

sign.o:sign.c
	gcc -c sign.c -o sign.o
