#ifndef _USR
#define _USR
#include "stdio.h"
#include "stdlib.h"
#include "string.h"

typedef struct User {
	char name[50];
	char password[50];
	struct User* next;
}user;

//saves the database of users in the specified file
//returns 0 if books were stored correctly, or an error code otherwise
void load_user(user* userhead);

//loads the database of users from the specified file
//the file must have been generated by a previous call to store_users()
//returns 0 if books were loaded correctly, or an error code otherwise
void save_user(user* userhead);
#endif










#endif